- name: Include the variables
  ansible.builtin.include_vars: configs/toolbox_vars.yaml

- name: Configure DNF {{ task_identifier }}
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      fastestmirror=True
      deltarpm=True
      max_parallel_downloads=10

- name: Add yarn repository {{ task_identifier }}
  ansible.builtin.yum_repository:
    name: yarn
    description: Yarn repository
    baseurl: https://dl.yarnpkg.com/rpm/
    enabled: true
    gpgcheck: true
    gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg

- name: Install common packages {{ task_identifier }}
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ dnf_common_packages }}"

- name: Ensure local directories exist {{ task_identifier }}
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"
  with_items:
    - "{{ github_local_dir }}"
    - "{{ ansible_user_dir }}/.local/bin"

- name: Install toolbox-vscode.git {{ task_identifier }}
  ansible.builtin.git:
    repo: https://github.com/owtaylor/toolbox-vscode.git
    dest: "{{ github_local_dir }}/toolbox-vscode"
    version: "HEAD"

- name: Create symlink to toolbox-vscode {{ task_identifier }}
  ansible.builtin.file:
    src: "{{ github_local_dir }}/toolbox-vscode/code.sh"
    dest: "{{ ansible_user_dir }}/.local/bin/code"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"

- name: Template out fish shell environment files {{ task_identifier }}
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/fish/conf.d/{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - {src: env.fish.j2, dest: 00env.fish}
    - {src: go.fish.j2, dest: 01go.fish}
    - {src: python.fish.j2, dest: 01python.fish}
    - {src: rust.fish.j2, dest: 01rust.fish}

- name: Create environment directories {{ task_identifier }}
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"
  with_items:
    - "{{ pipx_bin_dir }}"
    - "{{ pipx_home }}"
    - "{{ poetry_virtualenvs_path }}"
    - "{{ cargo_home }}"
    - "{{ ccache_dir }}"

- name: Install language servers globally {{ task_identifier }}
  community.general.yarn:
    name: "{{ item }}"
    global: true
  with_items: "{{ yarn_lsp_packages }}"

- name: Extract Go archive to {{ goroot }} {{ task_identifier }}
  ansible.builtin.unarchive:
    src: "https://go.dev.dl/go{{ go_version }}.tar.gz"
    dest: "{{ go_dest }}"
    remote_src: true
    creates: "{{ goroot }}/bin"
    mode: "0755"
