- name: nocturnal.local
  tasks:
    - playbooks/host/tasks_host_default.yaml
    - playbooks/host/tasks_host_rpm_ostree.yaml
    - playbooks/host/tasks_host_systemd.yaml
    - playbooks/host/tasks_host_python.yaml

  layered_packages:
    - bat
    - borgbackup
    - borgmatic
    - exa
    - fd-find
    - ffmpeg-libs
    - fish
    - fontconfig-enhanced-defaults
    - fontconfig-font-replacements
    - fzf
    - neovim
    - procs
    - ripgrep
    - rofi
    - rofimoji
    - snapper
    - starship
    - wireguard-tools
    - xclip
    - xfce4-genmon-plugin
    - xfce4-cpugraph-plugin

  borgmatic_repo: borg@azura.local:/bpool/borg/nocturnal
  borgmatic_hc_uuid: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65656136623131313337656538646435326132373662633464356666343534383239316462323665
    6532303633653336613239343936376363666363373964620a303033396433643330333665393131
    62353966633135623264346465353066626461626131306337303639616139383136343064616266
    3132666464333738320a386563383761643235343435613936343031636662663664343534313430
    39656633383237323961353163663637393961626332316432363034383438313866643734613931
    306562353264663030626264663265323134336434363938643

  etc_hosts:
    - "10.0.0.161 azura azura.local"
    - "10.0.0.119 peryite peryite.local"
    - "10.0.0.189 nocturnal nocturnal.local"

  user_dirs:
    - devel
    - devel/golang
    - devel/python
    - repos/github.com/hyperreal64
    - repos/pagure.io/hyperreal

  delete_dirs:
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

  xdg_user_dirs:
    desktop: desktop
    download: downloads
    templates: templates
    publicshare: public
    documents: documents
    music: misc/music
    pictures: sync/pictures
    videos: misc/videos

  systemd_services:
    - name: autoborg.timer
      state: started
      enabled: true
    - name: bluetooth.service
      state: started
      enabled: true
    - name: cups.service
      state: stopped
      enabled: false
    - name: lvm2-monitor.service
      state: stopped
      enabled: false
    - name: snapper-cleanup.timer
      state: started
      enabled: true
    - name: snapper-timeline.timer
      state: started
      enabled: true
