- name: fedora-toolbox-35
  image: registry.fedoraproject.org/fedora-toolbox:35
  shims:
    - flatpak
    - systemctl
    - rpm-ostree
    - podman
  tasks:
    - playbooks/common/tasks_dnf_full_upgrade.yaml
    - playbooks/common/tasks_toolbox_default.yaml
    - playbooks/common/tasks_toolbox_host_shims.yaml

- name: devel-python
  image: registry.fedoraproject.org/fedora-toolbox:35
  shims:
    - flatpak
    - systemctl
    - rpm-ostree
    - podman
  tasks:
    - playbooks/common/tasks_dnf_full_upgrade.yaml
    - playbooks/common/tasks_toolbox_default.yaml
    - playbooks/common/tasks_toolbox_host_shims.yaml
    - playbooks/toolbox/tasks_python_devel.yaml

- name: devel-fedora
  image: registry.fedoraproject.org/fedora-toolbox:35
  shims:
    - flatpak
    - systemctl
    - rpm-ostree
    - podman
  tasks:
    - playbooks/common/tasks_dnf_full_upgrade.yaml
    - playbooks/common/tasks_toolbox_default.yaml
    - playbooks/common/tasks_toolbox_host_shims.yaml
    - playbooks/toolbox/tasks_fedora_devel.yaml