pipx_home: /usr/local/pipx
pipx_bin_dir: /usr/local/pipx/venvs
poetry_virtualenvs_path: /opt/poetry
cargo_home: /opt/cargo
ccache_dir: /var/cache/ccache_rust

yarn_lsp_packages:
  - bash-language-server
  - dockerfile-language-server-nodejs
  - pyright
  - vscode-langservers-extracted
  - yaml-language-server

go_dest: /usr/local
go_version: 1.18.linux-amd64
goroot: "{{ go_dest }}/go"

github_local_dir: "{{ ansible_user_dir }}/repos/github.com"

dnf_common_packages:
  - "@c-development"
  - "@development-tools"
  - bat
  - cargo
  - cmake
  - code
  - curl
  - exa
  - fd-find
  - fish
  - fzf
  - gcc
  - git
  - git-core
  - glibc-langpack-en
  - glibc-locale-source
  - hugo
  - hyperfine
  - lsof
  - make
  - nc
  - mc
  - neovim
  - ninja-build
  - npm
  - openssl-devel
  - pipx
  - poetry
  - procs
  - python3-devel
  - python3-pip
  - restic
  - ripgrep
  - rsync
  - rust
  - starship
  - unzip
  - w3m
  - wget
  - xclip
  - zip

devel_python_packages:
  - libffi
  - libffi-devel

pipx_packages:
  - ansible-lint
  - black
  - bpython
  - flake8
  - howdoi
  - isort