---
- name: Setup host
  hosts: localhost
  vars:
    hostname: nocturnal.local
    relver: 36
    layered_packages:
      - borgbackup
      - borgmatic
      - ffmpeg-libs
      - fish
      - fontconfig-enhanced-defaults
      - fontconfig-font-replacements
      - fzf
      - neovim
      - rofi
      - rofimoji
      - snapper
      - wireguard-tools
      - xclip
      - xfce4-cpugraph-plugin
      - xfce4-genmon-plugin
      - xfce4-weather-plugin

    borgmatic_repo: borg@azura.local:/bpool/borg/nocturnal

    user_dirs:
      - bin
      - devel
      - devel/golang
      - devel/python
      - repos/github.com/hyperreal64
      - repos/pagure.io/hyperreal

    delete_dirs:
      - Desktop
      - Documents
      - Downloads
      - Music
      - Pictures
      - Public
      - Templates
      - Videos

    xdg_user_dirs:
      desktop: desktop
      download: downloads
      templates: misc/templates
      publicshare: public
      documents: sync/documents
      music: misc/music
      pictures: sync/pictures
      videos: misc/videos

    systemd_services:
      - name: autoborg.timer
        state: started
        enabled: true
      - name: bluetooth.service
        state: started
        enabled: true
      - name: cups.service
        state: stopped
        enabled: false
      - name: lvm2-monitor.service
        state: stopped
        enabled: false
      - name: snapper-cleanup.timer
        state: started
        enabled: true
      - name: snapper-timeline.timer
        state: started
        enabled: true

  tasks:
    - name: Set hostname 
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd
      become: true

    - name: Set sudo with no password
      tags: [sudo]
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ ansible_user_id }}"
        line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL"
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Create user directories in $HOME 
      tags: [xdg]
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0644"
      with_items: "{{ user_dirs }}"

    - name: Template out user-dirs.defaults 
      tags: [xdg]
      ansible.builtin.template:
        src: user-dirs.defaults.j2
        dest: /etc/xdg/user-dirs.defaults
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Delete unused directories in $HOME 
      tags: [xdg]
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/{{ item }}"
        state: absent
      with_items: "{{ delete_dirs }}"

    - name: Remove user-dirs.dirs from ~/.config 
      tags: [xdg]
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
        state: absent

    - name: Test if xdg-user-dirs-update command is available 
      tags: [xdg]
      ansible.builtin.command: command -v xdg-user-dirs-update
      register: xdg_user_dirs_update
      changed_when: false

    - name: Run xdg-user-dirs-update 
      tags: [xdg]
      ansible.builtin.command: "{{ xdg_user_dirs_update.stdout }}"
      when:
        - xdg_user_dirs_update.rc == 0

    - name: Ensure /etc/borgmatic directory exists 
      tags: [borg]
      ansible.builtin.file:
        path: /etc/borgmatic
        state: directory
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Template out borgmatic config 
      tags: [borg]
      ansible.builtin.template:
        src: borgmatic_config.yaml.j2
        dest: /etc/borgmatic/config.yaml
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Copy borgmatic systemd services 
      tags: [borg]
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: "0644"
      with_items:
        - autoborg.service
        - autoborg.timer
      become: true

    - name: Install rpm-gpg files to /etc/pki/rpm-gpg 
      ansible.builtin.copy:
        src: pki/
        dest: /etc/pki/
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Copy RPMFusion repository to /etc/yum.repos.d 
      ansible.builtin.copy:
        src: rpmfusion.repo
        dest: /etc/yum.repos.d/rpmfusion.repo
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Add dawid/better_fonts repository 
      ansible.builtin.get_url:
        url: "https://copr.fedorainfracloud.org/coprs/dawid/better_fonts/repo/fedora-{{ relver }}/dawid-better_fonts-fedora-{{ relver }}.repo"
        dest: "/etc/yum.repos.d/dawid-better_fonts-fedora-{{ relver }}.repo"
        mode: "0644"
      become: true

    - name: Install overlay packages 
      tags: [rpm-ostree]
      community.general.rpm_ostree_pkg:
        name: "{{ layered_packages }}"
        state: present
      register: rpm_ostree_pkg_install
      become: true

    - name: Change default user shell to fish
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/fish
      when:
        - rpm_ostree_apply_live.rc == 0
      become: true

    - name: Enable and start systemd system services 
      tags: [systemd]
      ansible.builtin.systemd:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        enabled: "{{ item.enabled }}"
        scope: system
      with_items: "{{ systemd_services }}"
      become: true
