---
- name: Setup host
  hosts: localhost
  vars:
    hostname: evergloam.local
    relver: 36
    layered_packages:
      - distrobox
      - ffmpeg-libs
      - fzf
      - mosh
      - neovim
      - rofi
      - rofimoji
      - snapper
      - wireguard-tools
      - xclip
      - xfce4-cpugraph-plugin
      - xfce4-genmon-plugin
      - xfce4-weather-plugin
      - zsh
   
    backup_host: apocrypha.local
    backup_recv_dir: /bpool/backups/evergloam

    user_dirs:
      - bin
      - devel
      - repos

    delete_dirs:
      - Desktop
      - Documents
      - Downloads
      - Music
      - Pictures
      - Public
      - Templates
      - Videos

    xdg_user_dirs:
      desktop: desktop
      download: downloads
      templates: misc/templates
      publicshare: public
      documents: sync/documents
      music: misc/music
      pictures: sync/pictures
      videos: misc/videos

    systemd_services:
      - name: backup_snapshot.timer
        state: started
        enabled: true
      - name: bluetooth.service
        state: started
        enabled: true
      - name: cups.service
        state: stopped
        enabled: false
      - name: lvm2-monitor.service
        state: stopped
        enabled: false

  tasks:
    - name: Variable check - hostname
      ansible.builtin.assert:
        that:
          - hostname is defined
          - hostname is string
        quiet: true

    - name: Variable check - relver
      ansible.builtin.assert:
        that:
          - relver is defined
          - relver is number
        quiet: true

    - name: Variable check - layered_packages
      ansible.builtin.assert:
        that:
          - layered_packages is defined
          - layered_packages is iterable
        quiet: true

    - name: Variable check - items in layered_packages
      ansible.builtin.assert:
        that:
          - item is defined
          - item is string
        quiet: true
      with_items: "{{ layered_packages }}"
      when:
        - layered_packages is defined

    - name: Variable check - user_dirs
      ansible.builtin.assert:
        that:
          - user_dirs is defined
          - user_dirs is iterable
        quiet: true

    - name: Variable check - items in user_dirs
      ansible.builtin.assert:
        that:
          - item is defined
          - item is string
        quiet: true
      with_items: "{{ user_dirs }}"
      when:
        - user_dirs is defined

    - name: Variable check - delete_dirs
      ansible.builtin.assert:
        that:
          - delete_dirs is defined
          - delete_dirs is iterable
        quiet: true

    - name: Variable check - items in delete_dirs
      ansible.builtin.assert:
        that:
          - item is defined
          - item is string
        quiet: true
      with_items: "{{ delete_dirs }}"
      when:
        - delete_dirs is defined

    - name: Variable check - xdg_user_dirs
      ansible.builtin.assert:
        that:
          - xdg_user_dirs is defined
          - xdg_user_dirs is mapping
          - xdg_user_dirs is iterable
        quiet: true

    - name: Variable check - systemd_services
      ansible.builtin.assert:
        that:
          - systemd_services is defined
          - systemd_services is iterable
        quiet: true

    - name: Variable check - items in systemd_services
      ansible.builtin.assert:
        that:
          - item.name is defined
          - item.name is string
          - item.state is defined
          - item.state is string
          - item.state in ["reloaded", "restarted", "started", "stopped"]
          - item.enabled is defined
          - item.enabled is boolean
        quiet: true
      with_items: "{{ systemd_services }}"
      when:
        - systemd_services is defined

    - name: Set hostname 
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd
      become: true

    - name: Set sudo with no password
      tags: [sudo]
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ ansible_user_id }}"
        line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL"
        owner: root
        group: root
        mode: "0644"
        create: true
      become: true

    - name: Create user directories in $HOME 
      tags: [xdg]
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0755"
      with_items: "{{ user_dirs }}"

    - name: Template out backup_snapshot.py
      tags: [backup]
      ansible.builtin.template:
        src: backup_snapshot.py.j2
        dest: /usr/local/bin/backup_snapshot.py
        owner: root
        group: root
        mode: "u+rwx,g+r,o+r"
      become: true

    - name: Copy backup_snapshot systemd unit files
      tags: [backup]
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: "0644"
      with_items:
        - backup_snapshot.service
        - backup_snapshot.timer
      become: true

    - name: Template out user-dirs.defaults 
      tags: [xdg]
      ansible.builtin.template:
        src: user-dirs.defaults.j2
        dest: /etc/xdg/user-dirs.defaults
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Delete unused directories in $HOME 
      tags: [xdg]
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/{{ item }}"
        state: absent
      with_items: "{{ delete_dirs }}"

    - name: Remove user-dirs.dirs from ~/.config 
      tags: [xdg]
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
        state: absent

    - name: Test if xdg-user-dirs-update command is available 
      tags: [xdg]
      ansible.builtin.command: command -v xdg-user-dirs-update
      register: xdg_user_dirs_update
      changed_when: false

    - name: Run xdg-user-dirs-update 
      tags: [xdg]
      ansible.builtin.command: "{{ xdg_user_dirs_update.stdout }}"
      when:
        - xdg_user_dirs_update.rc == 0
    
    - name: Install rpm-gpg files to /etc/pki/rpm-gpg 
      ansible.builtin.copy:
        src: pki/
        dest: /etc/pki/
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Copy RPMFusion repository to /etc/yum.repos.d 
      ansible.builtin.copy:
        src: rpmfusion.repo
        dest: /etc/yum.repos.d/rpmfusion.repo
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Add dawid/better_fonts repository 
      ansible.builtin.get_url:
        url: "https://copr.fedorainfracloud.org/coprs/dawid/better_fonts/repo/fedora-{{ relver }}/dawid-better_fonts-fedora-{{ relver }}.repo"
        dest: "/etc/yum.repos.d/dawid-better_fonts-fedora-{{ relver }}.repo"
        mode: "0644"
      become: true

    - name: Install overlay packages 
      tags: [rpm-ostree]
      community.general.rpm_ostree_pkg:
        name: "{{ layered_packages }}"
        state: present
      register: rpm_ostree_pkg_install
      become: true

    - name: Enable and start systemd system services 
      tags: [systemd]
      ansible.builtin.systemd:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        enabled: "{{ item.enabled }}"
        scope: system
      with_items: "{{ systemd_services }}"
      become: true
