---
- name: Setup default toolbox
  hosts: localhost
  vars:
    npm_lsp_packages:
      - bash-language-server
      - dockerfile-language-server-nodejs
      - pyright
      - vscode-langservers-extracted
      - yaml-language-server

    pipx_packages:
      - ansible-lint
      - black
      - bpython
      - howdoi
      - isort
      - pls
      - xonsh[full]

    dnf_packages:
      - "@c-development"
      - "@development-tools"
      - cargo
      - cmake
      - curl
      - fish
      - fzf
      - gcc
      - git
      - git-core
      - glibc-langpack-en
      - glibc-locale-source
      - golang
      - hugo
      - lsof
      - make
      - nc
      - mc
      - neovim
      - ninja-build
      - npm
      - openssl-devel
      - pipx
      - poetry
      - python3-devel
      - python3-pip
      - restic
      - rsync
      - rust
      - unzip
      - w3m
      - wget
      - xclip
      - zip

  tasks:
    - name: Variable check - npm_lsp_packages
      ansible.builtin.assert:
        that:
          - npm_lsp_packages is defined
          - npm_lsp_packages is iterable
        quiet: true

    - name: Variable check - items in npm_lsp_packages
      ansible.builtin.assert:
        that:
          - item is defined
          - item is string
        quiet: true
      loop: "{{ npm_lsp_packages }}"
      when:
        - npm_lsp_packages is defined

    - name: Variable check - pipx_packages
      ansible.builtin.assert:
        that:
          - pipx_packages is defined
          - pipx_packages is iterable
        quiet: true

    - name: Variable check - items in pipx_packages
      ansible.builtin.assert:
        that:
          - item is defined
          - item is string
        quiet: true
      loop: "{{ pipx_packages }}"
      when:
        - pipx_packages is defined

    - name: Variable check - dnf_packages
      ansible.builtin.assert:
        that:
          - dnf_packages is defined
          - dnf_packages is iterable
        quiet: true

    - name: Variable check - items in dnf_packages
      ansible.builtin.assert:
        that:
          - item is defined
          - item is string
        quiet: true
      loop: "{{ dnf_packages }}"
      when:
        - dnf_packages is defined

    - name: Configure DNF plugins 
      ansible.builtin.blockinfile:
        path: /etc/dnf/dnf.conf
        block: |
          fastestmirror=True
          deltarpm=True
          max_parallel_downloads=10
      become: true

    - name: Update all packages 
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
        update_only: true
      become: true

    - name: Install common packages 
      ansible.builtin.dnf:
        name: "{{ dnf_packages }}"
        state: present
      become: true

    - name: Install LSP packages globally 
      community.general.npm:
        name: "{{ item }}"
        state: present
        global: true
      with_items: "{{ npm_lsp_packages }}"
      become: true

    - name: Install Python packages with pipx 
      community.general.pipx:
        name: "{{ item }}"
        state: install
        install_deps: true
      with_items: "{{ pipx_packages }}"
