---
- name: Setup default toolbox
  hosts: localhost
  vars:
    shims:
      - flatpak
      - systemctl
      - rpm-ostree
      - podman

    npm_lsp_packages:
      - bash-language-server
      - dockerfile-language-server-nodejs
      - pyright
      - vscode-langservers-extracted
      - yaml-language-server

    pipx_packages:
      - ansible-lint
      - black
      - bpython
      - howdoi
      - isort
      - pls
      - xonsh[full]

    dnf_packages:
      - "@c-development"
      - "@development-tools"
      - cargo
      - cmake
      - curl
      - fish
      - fzf
      - gcc
      - git
      - git-core
      - glibc-langpack-en
      - glibc-locale-source
      - hugo
      - lsof
      - make
      - nc
      - mc
      - neovim
      - ninja-build
      - npm
      - openssl-devel
      - pipx
      - poetry
      - python3-devel
      - python3-pip
      - restic
      - rsync
      - rust
      - unzip
      - w3m
      - wget
      - xclip
      - zip

  tasks:
    - name: Configure DNF plugins 
      ansible.builtin.blockinfile:
        path: /etc/dnf/dnf.conf
        block: |
          fastestmirror=True
          deltarpm=True
          max_parallel_downloads=10
      become: true

    - name: Update all packages 
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
        update_only: true
      become: true

    - name: Install common packages 
      ansible.builtin.dnf:
        name: "{{ dnf_packages }}"
        state: present
      become: true

    - name: Copy host-runner to container 
      ansible.builtin.copy:
        src: host-runner.sh
        dest: /usr/local/bin/host-runner
        mode: a+x
      become: true

    - name: Create host-runner symbolic links 
      ansible.builtin.file:
        src: /usr/local/bin/host-runner
        dest: "/usr/local/bin/{{ executable }}"
        state: link
      loop: "{{ shims | default([]) }}"
      loop_control:
        loop_var: executable
      become: true

    - name: Install LSP packages globally 
      community.general.npm:
        name: "{{ item }}"
        state: present
        global: true
      with_items: "{{ npm_lsp_packages }}"
      become: true

    - name: Install Python packages with pipx 
      community.general.pipx:
        name: "{{ item }}"
        state: install
        install_deps: true
      with_items: "{{ pipx_packages }}"
