---
- name: Setup default toolbox
  hosts: localhost
  vars:
    npm_packages:
      - bash-language-server
      - dockerfile-language-server-nodejs
      - doctoc
      - markdown-styles
      - pyright
      - vscode-langservers-extracted
      - yaml-language-server

    pipx_packages:
      - ansible-lint
      - black
      - howdoi
      - isort
      - pls
      - xonsh[full]
  
    dnf_packages:
      - "@c-development"
      - "@development-tools"
      - cargo
      - cmake
      - curl
      - fzf
      - gcc
      - git
      - git-core
      - glibc-langpack-en
      - glibc-locale-source
      - golang
      - lsof
      - make
      - nc
      - mc
      - neovim
      - ninja-build
      - npm
      - openssh-server
      - openssl-devel
      - pipx
      - poetry
      - python3-devel
      - python3-pip
      - restic
      - rsync
      - rust
      - unzip
      - w3m
      - wget
      - xclip
      - zip

  tasks:
    - name: Variable check - npm_packages
      ansible.builtin.assert:
        that:
          - npm_packages is defined
          - npm_packages is iterable
        quiet: true

    - name: Variable check - items in npm_packages
      ansible.builtin.assert:
        that:
          - item is defined
          - item is string
        quiet: true
      loop: "{{ npm_packages }}"
      when:
        - npm_packages is defined

    - name: Variable check - pipx_packages
      ansible.builtin.assert:
        that:
          - pipx_packages is defined
          - pipx_packages is iterable
        quiet: true

    - name: Variable check - items in pipx_packages
      ansible.builtin.assert:
        that:
          - item is defined
          - item is string
        quiet: true
      loop: "{{ pipx_packages }}"
      when:
        - pipx_packages is defined

    - name: Variable check - dnf_packages
      ansible.builtin.assert:
        that:
          - dnf_packages is defined
          - dnf_packages is iterable
        quiet: true

    - name: Variable check - items in dnf_packages
      ansible.builtin.assert:
        that:
          - item is defined
          - item is string
        quiet: true
      loop: "{{ dnf_packages }}"
      when:
        - dnf_packages is defined

    - name: Configure DNF plugins 
      tags: [dnf]
      ansible.builtin.blockinfile:
        path: /etc/dnf/dnf.conf
        block: |
          fastestmirror=True
          deltarpm=True
          max_parallel_downloads=10
      become: true

    - name: Update all packages 
      tags: [dnf]
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
        update_only: true
      become: true

    - name: Install common packages 
      tags: [dnf]
      ansible.builtin.dnf:
        name: "{{ dnf_packages }}"
        state: present
      become: true

    - name: Install LSP packages globally 
      tags: [npm]
      community.general.npm:
        name: "{{ item }}"
        state: present
        global: true
      with_items: "{{ npm_packages }}"
      become: true

    - name: Install Python packages with pipx 
      tags: [pipx]
      community.general.pipx:
        name: "{{ item }}"
        state: install
        install_deps: true
      with_items: "{{ pipx_packages }}"

    - name: Generate RSA host key for SSH server
      tags: [ssh]
      ansible.builtin.shell: /usr/libexec/openssh/sshd-keygen rsa
      become: true

    - name: Generate ECDSA host key for SSH server
      tags: [ssh]
      ansible.builtin.shell: /usr/libexec/openssh/sshd-keygen ecdsa
      become: true

    - name: Generate ED25519 host key for SSH server
      tags: [ssh]
      ansible.builtin.shell: /usr/libexec/openssh/sshd-keygen ed25519
      become: true

    - name: Edit /etc/ssh/sshd_config for VSCode Remote - SSH
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Port 2222
          ListenAddress localhost
          PermitEmptyPasswords yes
      become: true
